# For documentation see here - https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
version: 0.2

phases:
  pre_build:
    commands:
      - temp_role=$(aws sts assume-role --role-arn "arn:aws:iam::$AWS_ACCOUNT_ID_NONPROD:role/$PIPELINE_BUILD_ROLE" --role-session-name "CodeBuildSession")
      - export AWS_ACCESS_KEY_ID=$(echo $temp_role | jq -r .Credentials.AccessKeyId)
      - export AWS_SECRET_ACCESS_KEY=$(echo $temp_role | jq -r .Credentials.SecretAccessKey)
      - export AWS_SESSION_TOKEN=$(echo $temp_role | jq -r .Credentials.SessionToken)
      - make docker-hub-signin
      - make docker-pull NAME=tester VERSION=latest
  build:
    commands:
      - make integration-test PROFILE=$PROFILE BUILD_BRANCH=$BUILD_BRANCH TAGS=$TAG PARALLEL_TEST_COUNT=20
    finally:
      - |
        if [ $CODEBUILD_BUILD_SUCCEEDING -eq 0 ]; then
          make slack-codebuild-notification BUILD_BRANCH=$BUILD_BRANCH PROFILE=$PROFILE PIPELINE_NAME="Test Task Environment" BUILD_STATUS=failure CODEBUILD_PROJECT_NAME=$CB_PROJECT_NAME CODEBUILD_BUILD_ID=$CODEBUILD_BUILD_ID SLACK_MESSAGE="Test Failed - Please investigate";
          exit 1;
        fi

reports:
  PytestIntegrationReport:
    files:
      - "testresults.json"
    base-directory: $CODEBUILD_SRC_DIR/test/integration
    discard-paths: yes
    file-format: CUCUMBERJSON
