PHARMACY_ORG_TYPE_ID = "PHA"
DENTIST_ORG_TYPE_ID = "Dentist"
SERVICE_TYPES_NAME_KEY = "SERVICE_TYPE_NAME"
ORGANISATION_SUB_TYPES_KEY = "ORGANISATION_SUB_TYPES"
VALID_SERVICE_TYPES_KEY = "VALID_SERVICE_TYPES"
ODSCODE_LENGTH_KEY = "ODSCODE_LENGTH"

SERVICE_TYPES = {
    PHARMACY_ORG_TYPE_ID: {
        ORGANISATION_SUB_TYPES_KEY: ["Community"],
        VALID_SERVICE_TYPES_KEY: [13, 131, 132, 134, 137],
        ODSCODE_LENGTH_KEY: 5,
    },
    DENTIST_ORG_TYPE_ID: {
        ORGANISATION_SUB_TYPES_KEY: ["TBA"],
        VALID_SERVICE_TYPES_KEY: [12],
        ODSCODE_LENGTH_KEY: 7,
    },
}
