PHARMACY_ORG_TYPE_ID = "PHA"
DENTIST_ORG_TYPE_ID = "Dentist"
ORGANISATION_SUB_TYPES_KEY = "ORGANISATION_SUB_TYPES"
VALID_SERVICE_TYPES_KEY = "VALID_SERVICE_TYPES"
ODSCODE_LENGTH_KEY = "ODSCODE_LENGTH"

SERVICE_TYPES = {
    PHARMACY_ORG_TYPE_ID: {
        ORGANISATION_SUB_TYPES_KEY: ["Community"],
        VALID_SERVICE_TYPES_KEY: [13, 131, 132, 134, 137],
        ODSCODE_LENGTH_KEY: 5,
    },
    DENTIST_ORG_TYPE_ID: {
        ORGANISATION_SUB_TYPES_KEY: ["TBA"],
        VALID_SERVICE_TYPES_KEY: [12],
        ODSCODE_LENGTH_KEY: 7,
    },
}


class ServiceTypeAliases:
    """Service Type Aliases for DoS Service Type Codes."""

    DENTIST_TYPE_ALIAS = "DENTIST"
    PHARMACY_TYPE_ALIAS = "PHARMACY"


# DoS Service Table Field Names
DOS_POSTCODE_FIELD_NAME = "postcode"
DOS_PUBLIC_PHONE_FIELD_NAME = "publicphone"
DOS_WEB_FIELD_NAME = "web"
DOS_ADDRESS_FIELD_NAME = "address"
DOS_TOWN_FIELD_NAME = "town"
DOS_TOWN_EASTING_NAME = "easting"
DOS_TOWN_NORTHING_NAME = "northing"
DOS_TOWN_LATITUDE_NAME = "latitude"
DOS_TOWN_LONGITUDE_NAME = "longitude"
# DoS Service History Table Key Names
DOS_POSTCODE_SERVICE_HISTORY_KEY = "postalcode"
DOS_PUBLIC_PHONE_SERVICE_HISTORY_KEY = "cmstelephoneno"
DOS_WEB_SERVICE_HISTORY_KEY = "cmsurl"
DOS_ADDRESS_SERVICE_HISTORY_KEY = "postaladdress"
DOS_ZCODE_SERVICE_HISTORY_KEY = "cmssgsdid"
DOS_SPECIFIED_OPENING_TIMES_SERVICE_HISTORY_KEY = "cmsopentimespecified"
DOS_STANDARD_OPENING_TIMES_MONDAY_SERVICE_HISTORY_KEY = "cmsopentimemonday"
DOS_STANDARD_OPENING_TIMES_TUESDAY_SERVICE_HISTORY_KEY = "cmsopentimetuesday"
DOS_STANDARD_OPENING_TIMES_WEDNESDAY_SERVICE_HISTORY_KEY = "cmsopentimewednesday"
DOS_STANDARD_OPENING_TIMES_THURSDAY_SERVICE_HISTORY_KEY = "cmsopentimethursday"
DOS_STANDARD_OPENING_TIMES_FRIDAY_SERVICE_HISTORY_KEY = "cmsopentimefriday"
DOS_STANDARD_OPENING_TIMES_SATURDAY_SERVICE_HISTORY_KEY = "cmsopentimesaturday"
DOS_STANDARD_OPENING_TIMES_SUNDAY_SERVICE_HISTORY_KEY = "cmsopentimesunday"
