PHARMACY_ORG_TYPE_ID = "PHA"
DENTIST_ORG_TYPE_ID = "Dentist"
ORGANISATION_SUB_TYPES_KEY = "ORGANISATION_SUB_TYPES"
VALID_SERVICE_TYPES_KEY = "VALID_SERVICE_TYPES"
ODSCODE_LENGTH_KEY = "ODSCODE_LENGTH"

SERVICE_TYPES = {
    PHARMACY_ORG_TYPE_ID: {
        ORGANISATION_SUB_TYPES_KEY: ["Community"],
        VALID_SERVICE_TYPES_KEY: [13, 131, 132, 134, 137],
        ODSCODE_LENGTH_KEY: 5,
    },
    DENTIST_ORG_TYPE_ID: {
        ORGANISATION_SUB_TYPES_KEY: ["TBA"],
        VALID_SERVICE_TYPES_KEY: [12],
        ODSCODE_LENGTH_KEY: 7,
    },
}

DENTIST_SUB_TYPE = SERVICE_TYPES[DENTIST_ORG_TYPE_ID][ORGANISATION_SUB_TYPES_KEY][0]
PHARMACY_SUB_TYPE = SERVICE_TYPES[PHARMACY_ORG_TYPE_ID][ORGANISATION_SUB_TYPES_KEY][0]


class ServiceTypeAliases:
    DENTIST_TYPE_ALIAS = "DENTIST"
    PHARMACY_TYPE_ALIAS = "PHARMACY"


DENTIST_SERVICE_TYPE_ALIAS = ServiceTypeAliases.DENTIST_TYPE_ALIAS
PHARMACY_SERVICE_TYPE_ALIAS = ServiceTypeAliases.PHARMACY_TYPE_ALIAS
