from dataclasses import dataclass

from .constants import (
    DOS_BLOOD_PRESSURE_SGSDID,
    DOS_BLOOD_PRESSURE_SYMPTOM_DISCRIMINATOR,
    DOS_BLOOD_PRESSURE_SYMPTOM_GROUP,
    DOS_BLOOD_PRESSURE_TYPE_ID,
    DOS_CONTRACEPTION_SGSDID,
    DOS_CONTRACEPTION_SYMPTOM_DISCRIMINATOR,
    DOS_CONTRACEPTION_SYMPTOM_GROUP,
    DOS_CONTRACEPTION_TYPE_ID,
    DOS_PALLIATIVE_CARE_SGSDID,
    DOS_PALLIATIVE_CARE_SYMPTOM_DISCRIMINATOR,
    DOS_PALLIATIVE_CARE_SYMPTOM_GROUP,
    DOS_PALLIATIVE_CARE_TYPE_ID,
    NHS_UK_BLOOD_PRESSURE_SERVICE_CODE,
    NHS_UK_CONTRACEPTION_SERVICE_CODE,
    NHS_UK_PALLIATIVE_CARE_SERVICE_CODE,
)


@dataclass
class CommissionedServiceType:
    """Class to represent constant values of a Service Type."""

    TYPE_NAME: str
    NHS_UK_SERVICE_CODE: str
    DOS_TYPE_ID: int
    DOS_SYMPTOM_GROUP: int
    DOS_SYMPTOM_DISCRIMINATOR: int
    DOS_SG_SD_ID: str

BLOOD_PRESSURE = CommissionedServiceType(
    TYPE_NAME="Blood Pressure",
    NHS_UK_SERVICE_CODE=NHS_UK_BLOOD_PRESSURE_SERVICE_CODE,
    DOS_TYPE_ID=DOS_BLOOD_PRESSURE_TYPE_ID,
    DOS_SYMPTOM_GROUP=DOS_BLOOD_PRESSURE_SYMPTOM_GROUP,
    DOS_SYMPTOM_DISCRIMINATOR=DOS_BLOOD_PRESSURE_SYMPTOM_DISCRIMINATOR,
    DOS_SG_SD_ID=DOS_BLOOD_PRESSURE_SGSDID,
)

CONTRACEPTION = CommissionedServiceType(
    TYPE_NAME="Contraception",
    NHS_UK_SERVICE_CODE=NHS_UK_CONTRACEPTION_SERVICE_CODE,
    DOS_TYPE_ID=DOS_CONTRACEPTION_TYPE_ID,
    DOS_SYMPTOM_GROUP=DOS_CONTRACEPTION_SYMPTOM_GROUP,
    DOS_SYMPTOM_DISCRIMINATOR=DOS_CONTRACEPTION_SYMPTOM_DISCRIMINATOR,
    DOS_SG_SD_ID=DOS_CONTRACEPTION_SGSDID,
)

PALLIATIVE_CARE = CommissionedServiceType(
    TYPE_NAME= "Pallivative Care",
    NHS_UK_SERVICE_CODE=NHS_UK_PALLIATIVE_CARE_SERVICE_CODE,
    DOS_TYPE_ID=DOS_PALLIATIVE_CARE_TYPE_ID,
    DOS_SYMPTOM_GROUP=DOS_PALLIATIVE_CARE_SYMPTOM_GROUP,
    DOS_SYMPTOM_DISCRIMINATOR=DOS_PALLIATIVE_CARE_SYMPTOM_DISCRIMINATOR,
    DOS_SG_SD_ID=DOS_PALLIATIVE_CARE_SGSDID,
)
