HIDDEN_OR_CLOSED_REPORT_ID = "HIDDEN_OR_CLOSED"
UN_MATCHED_PHARMACY_REPORT_ID = "UN_MATCHED_PHARMACY"
INVALID_POSTCODE_REPORT_ID = "INVALID_POSTCODE"
INVALID_OPEN_TIMES_REPORT_ID = "INVALID_OPEN_TIMES"

METRIC_REPORT_KEY_MAP = {
    "InvalidPostcode": INVALID_POSTCODE_REPORT_ID,
    "InvalidOpenTimes": INVALID_OPEN_TIMES_REPORT_ID,
}
