PHARMACY_SERVICE_KEY = "PHARMACY"
DENTIST_SERVICE_KEY = "DENTIST"
PHARMACY_ORG_TYPE_ID = "PHA"
DENTIST_ORG_TYPE_ID = "Dentist"
SERVICE_TYPES_ALIAS_KEY = "SERVICE_TYPE_NAME"
ORGANISATION_SUB_TYPES_KEY = "ORGANISATION_SUB_TYPES"
VALID_SERVICE_TYPES_KEY = "VALID_SERVICE_TYPES"
ODSCODE_LENGTH_KEY = "ODSCODE_LENGTH"

CLOSED_AND_HIDDEN_STATUSES = ["HIDDEN", "CLOSED"]

SERVICE_TYPES = {
    PHARMACY_ORG_TYPE_ID: {
        SERVICE_TYPES_ALIAS_KEY: PHARMACY_SERVICE_KEY,
        ORGANISATION_SUB_TYPES_KEY: ["Community"],
        VALID_SERVICE_TYPES_KEY: [13, 131, 132, 134, 137],
        ODSCODE_LENGTH_KEY: 5,
    },
    DENTIST_ORG_TYPE_ID: {
        SERVICE_TYPES_ALIAS_KEY: DENTIST_SERVICE_KEY,
        ORGANISATION_SUB_TYPES_KEY: ["TBA"],
        VALID_SERVICE_TYPES_KEY: [12],
        ODSCODE_LENGTH_KEY: 7,
    },
}

DENTIST_SERVICE_TYPE_IDS = SERVICE_TYPES[DENTIST_ORG_TYPE_ID][VALID_SERVICE_TYPES_KEY]
PHARMACY_SERVICE_TYPE_IDS = SERVICE_TYPES[PHARMACY_ORG_TYPE_ID][VALID_SERVICE_TYPES_KEY]

PHARMACY_SERVICE_TYPE_ID = 13

DOS_DEMOGRAPHICS_AREA_TYPE = "demographic"
DOS_CLINICAL_AREA_TYPE = "clinical"

DOS_POSTCODE_CHANGE_KEY = "postalcode"
DOS_WEBSITE_CHANGE_KEY = "cmsurl"
DOS_ADDRESS_CHANGE_KEY = "postaladdress"
DOS_PUBLIC_PHONE_CHANGE_KEY = "cmstelephoneno"
DOS_EASTING_CHANGE_KEY = "cmseastings"
DOS_NORTHING_CHANGE_KEY = "cmsnorthings"
DOS_POSTAL_TOWN_CHANGE_KEY = "cmsorgtown"
DI_LATITUDE_CHANGE_KEY = "latitude"  # DoS doesn't have a latitude change key so using one made up
DI_LONGITUDE_CHANGE_KEY = "longitude"  # DoS doesn't have a longitude change key so using one made up
DOS_SPECIFIED_OPENING_TIMES_CHANGE_KEY = "cmsopentimespecified"
DOS_STANDARD_OPENING_TIMES_MONDAY_CHANGE_KEY = "cmsopentimemonday"
DOS_STANDARD_OPENING_TIMES_TUESDAY_CHANGE_KEY = "cmsopentimetuesday"
DOS_STANDARD_OPENING_TIMES_WEDNESDAY_CHANGE_KEY = "cmsopentimewednesday"
DOS_STANDARD_OPENING_TIMES_THURSDAY_CHANGE_KEY = "cmsopentimethursday"
DOS_STANDARD_OPENING_TIMES_FRIDAY_CHANGE_KEY = "cmsopentimefriday"
DOS_STANDARD_OPENING_TIMES_SATURDAY_CHANGE_KEY = "cmsopentimesaturday"
DOS_STANDARD_OPENING_TIMES_SUNDAY_CHANGE_KEY = "cmsopentimesunday"
DOS_SGSDID_CHANGE_KEY = "cmssgsdid"

DOS_SERVICES_TABLE_CHANGE_TYPE_LIST = [
    DOS_ADDRESS_CHANGE_KEY,
    DOS_EASTING_CHANGE_KEY,
    DOS_NORTHING_CHANGE_KEY,
    DOS_POSTAL_TOWN_CHANGE_KEY,
    DOS_POSTCODE_CHANGE_KEY,
    DOS_PUBLIC_PHONE_CHANGE_KEY,
    DOS_WEBSITE_CHANGE_KEY,
]
DI_CHANGE_KEYS_LIST = [DI_LATITUDE_CHANGE_KEY, DI_LONGITUDE_CHANGE_KEY]

DOS_STANDARD_OPENING_TIMES_CHANGE_KEY_LIST = [
    DOS_STANDARD_OPENING_TIMES_MONDAY_CHANGE_KEY,
    DOS_STANDARD_OPENING_TIMES_TUESDAY_CHANGE_KEY,
    DOS_STANDARD_OPENING_TIMES_WEDNESDAY_CHANGE_KEY,
    DOS_STANDARD_OPENING_TIMES_THURSDAY_CHANGE_KEY,
    DOS_STANDARD_OPENING_TIMES_FRIDAY_CHANGE_KEY,
    DOS_STANDARD_OPENING_TIMES_SATURDAY_CHANGE_KEY,
    DOS_STANDARD_OPENING_TIMES_SUNDAY_CHANGE_KEY,
]

DI_CHANGE_ITEMS = [
    DOS_ADDRESS_CHANGE_KEY,
    DOS_EASTING_CHANGE_KEY,
    DOS_NORTHING_CHANGE_KEY,
    DOS_POSTAL_TOWN_CHANGE_KEY,
    DOS_POSTCODE_CHANGE_KEY,
    DOS_PUBLIC_PHONE_CHANGE_KEY,
    DOS_WEBSITE_CHANGE_KEY,
    DOS_STANDARD_OPENING_TIMES_MONDAY_CHANGE_KEY,
    DOS_STANDARD_OPENING_TIMES_TUESDAY_CHANGE_KEY,
    DOS_STANDARD_OPENING_TIMES_WEDNESDAY_CHANGE_KEY,
    DOS_STANDARD_OPENING_TIMES_THURSDAY_CHANGE_KEY,
    DOS_STANDARD_OPENING_TIMES_FRIDAY_CHANGE_KEY,
    DOS_STANDARD_OPENING_TIMES_SATURDAY_CHANGE_KEY,
    DOS_STANDARD_OPENING_TIMES_SUNDAY_CHANGE_KEY,
]
DOS_INTEGRATION_USER_NAME = "DOS_INTEGRATION"

DOS_PALLIATIVE_CARE_TYPE_ID = 13
NHS_UK_PALLIATIVE_CARE_SERVICE_CODE = "SRV0559"
DOS_PALLIATIVE_CARE_SYMPTOM_GROUP = 360
DOS_PALLIATIVE_CARE_SYMPTOM_DISCRIMINATOR = 14167
DOS_PHARMACY_NO_PALLIATIVE_CARE_TYPES = [131, 132, 134, 137]
DOS_PALLIATIVE_CARE_SGSDID = f"{DOS_PALLIATIVE_CARE_SYMPTOM_GROUP}={DOS_PALLIATIVE_CARE_SYMPTOM_DISCRIMINATOR}"
