###
# Pass - Creates Change Request
# NOTE: All date is fake and should not be used as a real change event.
POST http://localhost:9001/2015-03-31/functions/function/invocations HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "SearchKey": "ANEI1245",
  "ODSCode": "FQ038",
  "OrganisationName": "My Test Pharmacy",
  "OrganisationTypeId": "PH1",
  "OrganisationType": "Pharmacy",
  "OrganisationStatus": "Visible",
  "ServiceType": "PHA",
  "ServiceSubType": "COMPH",
  "SummaryText": "",
  "URL": "https://my-pharmacy.com/",
  "Address1": "85 Peachfield Road",
  "Address2": null,
  "Address3": null,
  "City": "CHAPEL ROW",
  "County": "South Godshire",
  "Latitude": 53.38030624389648,
  "Longitude": -1.4826949834823608,
  "Postcode": "RG7 1DB",
  "Phone": "123456789",
  "Email": "health.my-pharmacy@nhs.net",
  "Website": "https://my-pharmacy.com/health-service",
  "OrganisationSubType": null,
  "OrganisationAliases": []
}

###
# Pass - No Change Request as data matches DoS
# NOTE: All date is fake and should not be used as a real change event.
POST http://localhost:9001/2015-03-31/functions/function/invocations HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "SearchKey": "ANEI1245",
  "ODSCode": "06K 06N",
  "OrganisationName": "",
  "OrganisationTypeId": "PH1",
  "OrganisationType": "Pharmacy",
  "OrganisationStatus": "Visible",
  "ServiceType": "PHA",
  "ServiceSubType": "COMPH",
  "SummaryText": "",
  "URL": "https://my-pharmacy.com/",
  "Address1": "Charter House",
  "Address2": "Parkway",
  "Address3": "Welwyn Garden City",
  "City": "",
  "County": "",
  "Latitude": 53.38030624389648,
  "Longitude": -1.4826949834823608,
  "Postcode": "AL8 6JL",
  "Phone": "01278 422011",
  "Email": "health.my-pharmacy@nhs.net",
  "Website": "www.boots.com",
  "OrganisationSubType": "",
  "OrganisationAliases": []
}


###
# Pass - No DoS Matches
# NOTE: All date is fake and should not be used as a real change event.
POST http://localhost:9001/2015-03-31/functions/function/invocations HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "SearchKey": "ANEI1245",
  "ODSCode": "FXXX1",
  "OrganisationName": "My Test Pharmacy",
  "OrganisationTypeId": "PH1",
  "OrganisationType": "Pharmacy",
  "OrganisationStatus": "Visible",
  "ServiceType": "PHA",
  "ServiceSubType": "COMPH",
  "SummaryText": "",
  "URL": "https://my-pharmacy.com/",
  "Address1": "85 Peachfield Road",
  "Address2": null,
  "Address3": null,
  "City": "CHAPEL ROW",
  "County": "South Godshire",
  "Latitude": 53.38030624389648,
  "Longitude": -1.4826949834823608,
  "Postcode": "RG7 1DB",
  "Phone": "123456789",
  "Email": "health.my-pharmacy@nhs.net",
  "Website": "https://my-pharmacy.com/health-service",
  "OrganisationSubType": null,
  "OrganisationAliases": []
}
