from application.common.constants import (
    DOS_BLOOD_PRESSURE_SGSDID,
    DOS_BLOOD_PRESSURE_SYMPTOM_DISCRIMINATOR,
    DOS_BLOOD_PRESSURE_SYMPTOM_GROUP,
    DOS_BLOOD_PRESSURE_TYPE_ID,
    DOS_CONTRACEPTION_SGSDID,
    DOS_CONTRACEPTION_SYMPTOM_DISCRIMINATOR,
    DOS_CONTRACEPTION_SYMPTOM_GROUP,
    DOS_CONTRACEPTION_TYPE_ID,
)
from application.common.service_type import BLOOD_PRESSURE, CONTRACEPTION


def test_blood_pressure_service_type():
    assert BLOOD_PRESSURE.TYPE_NAME == "Blood Pressure"
    assert BLOOD_PRESSURE.NHS_UK_SERVICE_CODE == "SRV0560"
    assert BLOOD_PRESSURE.DOS_TYPE_ID == DOS_BLOOD_PRESSURE_TYPE_ID
    assert BLOOD_PRESSURE.DOS_SYMPTOM_GROUP == DOS_BLOOD_PRESSURE_SYMPTOM_GROUP
    assert BLOOD_PRESSURE.DOS_SYMPTOM_DISCRIMINATOR == DOS_BLOOD_PRESSURE_SYMPTOM_DISCRIMINATOR
    assert BLOOD_PRESSURE.DOS_SG_SD_ID == DOS_BLOOD_PRESSURE_SGSDID


def test_contraception_service_type():
    assert CONTRACEPTION.TYPE_NAME == "Contraception"
    assert CONTRACEPTION.NHS_UK_SERVICE_CODE == "SRV2000"
    assert CONTRACEPTION.DOS_TYPE_ID == DOS_CONTRACEPTION_TYPE_ID
    assert CONTRACEPTION.DOS_SYMPTOM_GROUP == DOS_CONTRACEPTION_SYMPTOM_GROUP
    assert CONTRACEPTION.DOS_SYMPTOM_DISCRIMINATOR == DOS_CONTRACEPTION_SYMPTOM_DISCRIMINATOR
    assert CONTRACEPTION.DOS_SG_SD_ID == DOS_CONTRACEPTION_SGSDID
