from application.common.commissioned_service_type import BLOOD_PRESSURE, CONTRACEPTION, PALLIATIVE_CARE
from application.common.constants import (
    DOS_BLOOD_PRESSURE_SGSDID,
    DOS_BLOOD_PRESSURE_SYMPTOM_DISCRIMINATOR,
    DOS_BLOOD_PRESSURE_SYMPTOM_GROUP,
    DOS_BLOOD_PRESSURE_TYPE_ID,
    DOS_CONTRACEPTION_SGSDID,
    DOS_CONTRACEPTION_SYMPTOM_DISCRIMINATOR,
    DOS_CONTRACEPTION_SYMPTOM_GROUP,
    DOS_CONTRACEPTION_TYPE_ID,
    DOS_PALLIATIVE_CARE_SGSDID,
    DOS_PALLIATIVE_CARE_SYMPTOM_DISCRIMINATOR,
    DOS_PALLIATIVE_CARE_SYMPTOM_GROUP,
    DOS_PALLIATIVE_CARE_TYPE_ID,
)


def test_blood_pressure_commissioned_service_type():
    assert BLOOD_PRESSURE.TYPE_NAME == "Blood Pressure"
    assert BLOOD_PRESSURE.NHS_UK_SERVICE_CODE == "SRV0560"
    assert BLOOD_PRESSURE.DOS_TYPE_ID == DOS_BLOOD_PRESSURE_TYPE_ID
    assert BLOOD_PRESSURE.DOS_SYMPTOM_GROUP == DOS_BLOOD_PRESSURE_SYMPTOM_GROUP
    assert BLOOD_PRESSURE.DOS_SYMPTOM_DISCRIMINATOR == DOS_BLOOD_PRESSURE_SYMPTOM_DISCRIMINATOR
    assert BLOOD_PRESSURE.DOS_SG_SD_ID == DOS_BLOOD_PRESSURE_SGSDID


def test_contraception_commissioned_service_type():
    assert CONTRACEPTION.TYPE_NAME == "Contraception"
    assert CONTRACEPTION.NHS_UK_SERVICE_CODE == "SRV2000"
    assert CONTRACEPTION.DOS_TYPE_ID == DOS_CONTRACEPTION_TYPE_ID
    assert CONTRACEPTION.DOS_SYMPTOM_GROUP == DOS_CONTRACEPTION_SYMPTOM_GROUP
    assert CONTRACEPTION.DOS_SYMPTOM_DISCRIMINATOR == DOS_CONTRACEPTION_SYMPTOM_DISCRIMINATOR
    assert CONTRACEPTION.DOS_SG_SD_ID == DOS_CONTRACEPTION_SGSDID


def test_pallative_care_commissioned_service_type():
    assert PALLIATIVE_CARE.TYPE_NAME == "Pallivative Care"
    assert PALLIATIVE_CARE.NHS_UK_SERVICE_CODE == "SRV0559"
    assert PALLIATIVE_CARE.DOS_TYPE_ID == DOS_PALLIATIVE_CARE_TYPE_ID
    assert PALLIATIVE_CARE.DOS_SYMPTOM_GROUP == DOS_PALLIATIVE_CARE_SYMPTOM_GROUP
    assert PALLIATIVE_CARE.DOS_SYMPTOM_DISCRIMINATOR == DOS_PALLIATIVE_CARE_SYMPTOM_DISCRIMINATOR
    assert PALLIATIVE_CARE.DOS_SG_SD_ID == DOS_PALLIATIVE_CARE_SGSDID
