###
# Pass
# NOTE: All date is fake and should not be used as a real change event.
POST http://localhost:9000/2015-03-31/functions/function/invocations HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "body": {
    "SearchKey": "ANEI1245",
    "ODSCode": "FX111",
    "OrganisationName": "My Test Pharmacy",
    "OrganisationTypeId": "PH1",
    "OrganisationType": "Pharmacy",
    "OrganisationStatus": "Visible",
    "SummaryText": "",
    "URL": "https://my-pharmacy.com/",
    "Address1": "85 Peachfield Road",
    "Address2": null,
    "Address3": null,
    "City": "CHAPEL ROW",
    "County": "South Godshire",
    "Latitude": 53.38030624389648,
    "Longitude": -1.4826949834823608,
    "Postcode": "RG7 1DB",
    "Phone": "123456789",
    "Email": "health.my-pharmacy@nhs.net",
    "Website": "https://my-pharmacy.com/health-service",
    "OrganisationSubType": null,
    "OrganisationAliases": []
  }
}

###
# Fail - Incorrect event format (no body)
# NOTE: All date is fake and should not be used as a real change event.
POST http://localhost:9000/2015-03-31/functions/function/invocations HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "SearchKey": "ANEI1245",
  "ODSCode": "FX111",
  "OrganisationName": "My Test Pharmacy",
  "OrganisationTypeId": "PH1",
  "OrganisationType": "Not a Pharmacy",
  "OrganisationStatus": "Visible",
  "SummaryText": "",
  "URL": "https://my-pharmacy.com/",
  "Address1": "85 Peachfield Road",
  "Address2": null,
  "Address3": null,
  "City": "CHAPEL ROW",
  "County": "South Godshire",
  "Latitude": 53.38030624389648,
  "Longitude": -1.4826949834823608,
  "Postcode": "RG7 1DB",
  "Phone": "123456789",
  "Email": "health.my-pharmacy@nhs.net",
  "Website": "https://my-pharmacy.com/health-service",
  "OrganisationSubType": null,
  "OrganisationAliases": []
}

###
# Fail - missing organisation type
# NOTE: All date is fake and should not be used as a real change event.
POST http://localhost:9000/2015-03-31/functions/function/invocations HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "body": {
    "SearchKey": "ANEI1245",
    "ODSCode": "FX111",
    "OrganisationName": "My Test Pharmacy",
    "OrganisationTypeId": "PH1",
    "OrganisationStatus": "Visible",
    "SummaryText": "",
    "URL": "https://my-pharmacy.com/",
    "Address1": "85 Peachfield Road",
    "Address2": null,
    "Address3": null,
    "City": "CHAPEL ROW",
    "County": "South Godshire",
    "Latitude": 53.38030624389648,
    "Longitude": -1.4826949834823608,
    "Postcode": "RG7 1DB",
    "Phone": "123456789",
    "Email": "health.my-pharmacy@nhs.net",
    "Website": "https://my-pharmacy.com/health-service",
    "OrganisationSubType": null,
    "OrganisationAliases": []
  }
}

###
# Fail - missing organisation type
# NOTE: All date is fake and should not be used as a real change event.
POST http://localhost:9000/2015-03-31/functions/function/invocations HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "body": {
    "SearchKey": "ANEI1245",
    "ODSCode": "FX111",
    "OrganisationName": "My Test Pharmacy",
    "OrganisationTypeId": "PH1",
    "OrganisationType": "Not a Pharmacy",
    "OrganisationStatus": "Visible",
    "SummaryText": "",
    "URL": "https://my-pharmacy.com/",
    "Address1": "85 Peachfield Road",
    "Address2": null,
    "Address3": null,
    "City": "CHAPEL ROW",
    "County": "South Godshire",
    "Latitude": 53.38030624389648,
    "Longitude": -1.4826949834823608,
    "Postcode": "RG7 1DB",
    "Phone": "123456789",
    "Email": "health.my-pharmacy@nhs.net",
    "Website": "https://my-pharmacy.com/health-service",
    "OrganisationSubType": null,
    "OrganisationAliases": []
  }
}
