# General
DEFAULT_ODS_CODE = "FC766"

# Service Statuses
DOS_ACTIVE_STATUS_ID = 1
DOS_CLOSED_STATUS_ID = 2

# Blood Pressure
DOS_BLOOD_PRESSURE_TYPE_ID = 148
NHS_UK_BLOOD_PRESSURE_SERVICE_CODE = "SRV0560"

# Contraception
DOS_CONTRACEPTION_TYPE_ID = 149
NHS_UK_CONTRACEPTION_SERVICE_CODE = "SRV2000"
