version: 0.2

#env:
  #variables:
    # key: "value"
    # key: "value"
  #parameter-store:
    # key: "value"
    # key: "value"
  #secrets-manager:
    # key: secret-id:json-key:version-stage:version-id
    # key: secret-id:json-key:version-stage:version-id
  #exported-variables:
    # - variable
    # - variable
  #git-credential-helper: yes
#batch:
  #fast-fail: true
  #build-list:
  #build-matrix:
  #build-graph:
phases:
  install:
    runtime-versions:
      docker: 19
  #install:
    #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.
    #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.
    #runtime-versions:
      # name: version
      # name: version
    #commands:
      # - command
      # - command
  pre_build:
    commands:
      - make docker-hub-signin
      - docker --version
      - docker-compose --version
      - curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      - chmod +x /usr/local/bin/docker-compose
      - docker-compose --version
  build:
    commands:
      - make tester-build
      - make update-ip-allowlist PROFILE=test ENVIRONMENT=test USERNAME="codebuild"
      - make terraform-apply-auto-approve STACKS=api-gateway-sqs PROFILE=test ENVIRONMENT=test
      - make integration-test TAGS=complete PROFILE=test ENVIRONMENT=test RUN_ID=$CODEBUILD_RESOLVED_SOURCE_VERSION-$CODEBUILD_BUILD_NUMBER PARALLEL_TEST_COUNT=8
  post_build:
    commands:
      - make delete-ip-from-allowlist PROFILE=test ENVIRONMENT=test USERNAME="codebuild"
reports: #New
  PytestIntegrationReport: # CodeBuild will create a report group called "PytestIntegrationReport".
    files: #Store all of the files
      - '**/*'
    base-directory: $CODEBUILD_SRC_DIR/test/integration
    discard-paths: yes
    file-format: JUNITXML
#artifacts:
  #files:
    # - location
    # - location
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths
